FROM registry.access.redhat.com/dotnet/dotnet-22-rhel7:2.2-2
# This image provides a .NET Core 2.1 environment you can use to run your .NET
# applications.

USER 0

# Install Java JDK 8
RUN yum -y install java-1.8.0-openjdk

RUN chown -R 1001:0 /opt/app-root && chown -R 1001:0 $HOME && \
    chmod -R ug+rwX /opt/app-root

USER 1001
