kind: Template
apiVersion: v1
metadata:
  annotations:
    description: |
      Deployment template for a mariadb server with persistent storage.
  name: "${NAME}-template"
objects:
- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: "matomo-data"
    labels:
      app: "${NAME}"
  spec:
    storageClassName: "${PERSISTENT_VOLUME_CLASS}"
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: "${PERSISTENT_VOLUME_SIZE}"
- kind: Service
  apiVersion: v1
  metadata:
    name: "${NAME}"
    labels:
      app: "${NAME}"
    annotations:
      template.openshift.io/expose-uri: mysql://{.spec.clusterIP}:{.spec.ports[?(.name=="mariadb")].port}
  spec:
    ports:
    - name: 3306-tcp
      protocol: TCP
      port: 3306
      targetPort: 3306
    selector:
      app: "${NAME}"
    type: ClusterIP
    sessionAffinity: None
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: "${NAME}"
    labels:
      app: "${NAME}"
      role: "db"
  spec:
    strategy:
      type: Recreate
      recreateParams:
        timeoutSeconds: 600
      activeDeadlineSeconds: 21600
    triggers:
      - type: ConfigChange
    replicas: 1
    selector:
      app: "${NAME}"
      role: db
    template:
      metadata:
        labels:
          app: "${NAME}"
          role: db
      spec:
        volumes:
          - name: "data"
            persistentVolumeClaim:
              claimName: "matomo-data"
        containers:
          - name: "${NAME}"
            image: "image-registry.openshift-image-registry.svc:5000/${SOURCE_IMAGE_NAMESPACE}/${SOURCE_IMAGE_NAME}:${SOURCE_IMAGE_TAG}"
            ports:
              - name: server-port
                containerPort: 3306
                protocol: TCP
            envFrom:
              - secretRef:
                  name: matomo-creds
            resources:
              requests:
                cpu: "${CPU_REQUEST}"
                memory: "${MEMORY_REQUEST}"
              limits:
                cpu: "${CPU_LIMIT}"
                memory: "${MEMORY_LIMIT}"
            volumeMounts:
              - name: "data"
                mountPath: /var/lib/mysql/data
            livenessProbe:
              tcpSocket:
                port: 3306
              initialDelaySeconds: 30
              timeoutSeconds: 1
              periodSeconds: 10
              successThreshold: 1
              failureThreshold: 3
            readinessProbe:
              exec:
                command:
                - "/bin/sh"
                - "-i"
                - "-c"
                - MYSQL_PWD="$MYSQL_PASSWORD" mysql -h 127.0.0.1 -u $MYSQL_USER -D $MYSQL_DATABASE
                  -e 'SELECT 1'
              initialDelaySeconds: 5
              timeoutSeconds: 1
              periodSeconds: 10
              successThreshold: 1
              failureThreshold: 3
            terminationMessagePath: "/dev/termination-log"
            terminationMessagePolicy: File
            imagePullPolicy: IfNotPresent
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
parameters:
- name: NAME
  displayName: Name
  description: The name assigned to all of the OpenShift resources associated to the
    server instance.
  required: true
  value: mariadb
- name: SOURCE_IMAGE_NAMESPACE
  displayName: Image Namespace
  required: true
  description: The namespace of the OpenShift project containing the imagestream for
    the application.
  value: fd34fb-tools
- name: SOURCE_IMAGE_NAME
  displayName: Source Image Name
  description: The name of the image to use for this resource.
  required: true
  value: mariadb
- name: SOURCE_IMAGE_TAG
  displayName: Environment TAG name
  description: The TAG name for this environment, e.g., dev, test, prod
  required: true
  value: latest
- name: PERSISTENT_VOLUME_SIZE
  displayName: Persistent Volume Size
  description: The size of the persistent volume , e.g. 512Mi, 1Gi, 2Gi.
  required: true
  value: "1Gi"
- name: PERSISTENT_VOLUME_CLASS
  displayName: Persistent Volume Class name
  description: The class of the volume; gluster-file, gluster-block, gluster-file-db
  required: false
  value: netapp-file-standard
- name: CPU_REQUEST
  displayName: Resources CPU Request
  description: The resources CPU request (in cores) for this build.
  required: true
  value: "100m"
- name: CPU_LIMIT
  displayName: Resources CPU Limit
  description: The resources CPU limit (in cores) for this build.
  required: true
  value: 250m
- name: MEMORY_REQUEST
  displayName: Resources Memory Request
  description: The resources Memory request (in Mi, Gi, etc) for this build.
  required: true
  value: 100Mi
- name: MEMORY_LIMIT
  displayName: Resources Memory Limit
  description: The resources Memory limit (in Mi, Gi, etc) for this build.
  required: true
  value: 512Mi
