kind: Template
apiVersion: v1
metadata:
  name: "${NAME}-build-template"
  creationTimestamp: 
objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: "${NAME}"
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: "${NAME}"
    labels:
      app: "${NAME}"
  spec:
    triggers:
    - type: ImageChange
    - type: ConfigChange
    runPolicy: Serial
    source:
      type: Git
      git:
        uri: "${SOURCE_REPOSITORY_URL}"
        ref: "${SOURCE_REPOSITORY_REF}"
      contextDir: "${SOURCE_CONTEXT_DIR}"
    strategy:
      type: Docker
      dockerStrategy:
        from:
          kind: DockerImage
          name: registry.access.redhat.com/dotnet/dotnet-21-rhel7:latest
        dockerfilePath: "${DOCKER_FILE_PATH}"
    output:
      to:
        kind: ImageStreamTag
        name: "${NAME}:${OUTPUT_IMAGE_TAG}"
parameters:
- name: NAME
  displayName: Name
  description: The name assigned to all of the resources defined in this template.
  required: false
  value: dotnet-sonar
- name: SOURCE_REPOSITORY_URL
  displayName: Git Repo URL
  description: The URL to your GIT repo.
  required: true
  value: https://github.com/bcgov/bcdevexchange.git
- name: SOURCE_REPOSITORY_REF
  displayName: Git Reference
  description: The git reference or branch.
  required: true
  value: develop
- name: SOURCE_CONTEXT_DIR
  displayName: Source Context Directory
  description: The source context directory.
  required: false
  value: "dotnet-sonar"
- name: SOURCE_IMAGE_KIND
  displayName: Source Image Kind
  description: The 'kind' (type) of the  source image; typically ImageStreamTag, or
    DockerImage.
  required: false
  value: ImageStreamTag 
- name: SOURCE_IMAGE_NAME
  displayName: Source Image Name
  description: The name of the source image.
  required: false
  value: registry.access.redhat.com/dotnet/dotnet-22-rhel7
- name: SOURCE_IMAGE_TAG
  displayName: Source Image Tag
  description: The tag of the source image.
  required: false
  value: 2.2-2
- name: DOCKER_FILE_PATH
  displayName: Docker File Path
  description: The path to the docker file defining the build.
  required: false
  value: Dockerfile.RHEL
- name: OUTPUT_IMAGE_TAG
  displayName: Output Image Tag
  description: The tag given to the built image.
  required: false
  value: latest